# Generated by Django 4.2.19 on 2025-09-06 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_blogpost_thumbnail"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Blogpost",
        ),
    ]
