# Generated by Django 4.2.19 on 2025-09-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="orderUpdate",
            fields=[
                ("update_id", models.AutoField(primary_key=True, serialize=False)),
                ("order_id", models.IntegerField(default="")),
                ("update_desc", models.CharField(max_length=5000)),
                ("timestamp", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="product",
            name="id",
        ),
        migrations.AddField(
            model_name="orders",
            name="amount",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="orders",
            name="phone",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="product",
            name="product_id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
